### ISSUE TITLE
在线版本：https://nav.678668.xyz/

### ISSUE THREAD

**Issue by zhuima** [weijunext/indie-hacker-tools#10]
找了一个别人写的导航站，改了改,基于Next.js 13 +  Tailwind

在线版本：https://nav.678668.xyz/

icon获取是使用RPA + https://icon.horse/ 批量抓的，可能会有误差
markdown转json是基于ChatGPT自动问答得到的
网站托管在Vercel, 域名解析在cloudflare

**Comment by weijunext** [comment]
> 找了一个别人写的导航站，改了改,基于Next.js 13 + Tailwind
> 
> 在线版本：https://nav.678668.xyz/
> 
> icon获取是使用RPA + https://icon.horse/ 批量抓的，可能会有误差 markdown转json是基于ChatGPT自动问答得到的 网站托管在Vercel, 域名解析在cloudflare

加到 `README.md` 了。可以考虑换个域名～

**Comment by zhuima** [comment]
域名已更新：https://chuhai.tools/
