### ISSUE TITLE
自荐自己的开源工具：VitePressSimple,可视化配置vitepress的客户端工具

### ISSUE THREAD

**Issue by zhangdi168** [weijunext/indie-hacker-tools#39]
**zhangdi-[Github](https://github.com/zhangdi168)

- [VitePressSimple-github](https://github.com/zhangdi168/VitePressSimple):一个基于wails2开发的vitepress可视化写作、可视化配置编辑的客户端工具，助力独立开发者快速搭建自己的产品手册或博客（开源、免费！）。 [官网](http://vpsimple.xiaod.co/), [快速入门使用视频](https://www.bilibili.com/video/BV1ki421y7uV/?spm_id_from=333.999.0.0)

**Comment by weijunext** [comment]
已收录
