### ISSUE TITLE
需要一个好用的 app landing page 模板

### ISSUE THREAD

**Issue by zhihuij** [weijunext/indie-hacker-tools#5]
春节做了个 ios app，想做个 landing page，只找到个能用的：https://github.com/zhihuij/app-landing-pages 但在大屏以及移动端上展示不尽如人意，求推荐

**Comment by zhuima** [comment]
落地页这个想要美观、多端兼容、动画完备之类的还是要买模版，当前已有的开源的都是要花些时间和精力去不断完善

**Comment by NMTuan** [comment]
看这里 https://themeforest.net/category/marketing/landing-pages

**Comment by zhihuij** [comment]
感谢上面两位，我打算直接基于 https://vitepress.dev/ 这个页面去改

**Comment by zhuima** [comment]
1000+ Landing page 任你选，快来看看，https://htmlrev.com/

**Comment by weijunext** [comment]
[Landing Page模板](https://github.com/weijunext/indie-hacker-tools?tab=readme-ov-file#landing-page-%E6%A8%A1%E6%9D%BF)
